# Generated by Django 4.2.5 on 2023-09-20 14:12

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='myPosts')),
                ('caption', models.TextField()),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('noOfLikes', models.IntegerField(default=0)),
            ],
        ),
    ]
