# Generated by Django 4.2.5 on 2023-09-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='likedpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.CharField(max_length=50)),
                ('likedBy', models.CharField(max_length=50)),
            ],
        ),
    ]
