# Generated by Django 4.2.5 on 2023-09-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_likedpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='followersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followedBy', models.CharField(max_length=500)),
                ('gotFollowedBy', models.CharField(max_length=500)),
            ],
        ),
    ]
